#!/usr/bin/env python3

import sys
import os

if len(sys.argv) - 1 != 1:
    sys.stderr.write("Usage: %s <run_id>\n" % sys.argv[0])
    sys.exit(1)

run_id = sys.argv[1]

cmd = "(ps -ef | grep __catrunner_%s__ | grep -v grep | awk '{print $2}' | xargs pkill -P 2>/dev/null) && touch run_status/is_manually_stopped_%s" % (run_id, run_id)
os.system(cmd)

print("Successfully stopped %s" % run_id)
